//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBPORTAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class Employer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employer()
        {
            this.EmployerSelectsSeekers = new HashSet<EmployerSelectsSeeker>();
            this.Jobs = new HashSet<Job>();
            this.JobAppoinments = new HashSet<JobAppoinment>();
            this.JobSeekers = new HashSet<JobSeeker>();
        }
    
        public int EmployerId { get; set; }
        [Required(ErrorMessage = "User Name is Required")]
        public string EmployerUsername { get; set; }
        [Required(ErrorMessage = "Name is Required")]
        public string EmployerName { get; set; }
        [Required(ErrorMessage = "Contact number is Required")]
        public string EmployerContactNo { get; set; }
        [Required(ErrorMessage = "Email is Required")]
        public string EmployerEmail { get; set; }
        [Required(ErrorMessage = "Password is Required")]
        [DataType(DataType.Password)]
        public string EmployerPassword { get; set; }
        public string ProfilePictureName { get; set; }
        public string CompanyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployerSelectsSeeker> EmployerSelectsSeekers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobAppoinment> JobAppoinments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeeker> JobSeekers { get; set; }
    }
}
