//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBPORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.JobAppoinments = new HashSet<JobAppoinment>();
            this.JobSeekeds = new HashSet<JobSeeked>();
        }
    
        public int JobId { get; set; }
        public string JobName { get; set; }
        public string JobRequirements { get; set; }
        public string JobDescription { get; set; }
        public string JobPosition { get; set; }
        public string JobLocation { get; set; }
        public Nullable<decimal> JobSalary { get; set; }
        public double JobWorkingHour { get; set; }
        public int EmployerId { get; set; }
        public int JobCategoryId { get; set; }
    
        public virtual Employer Employer { get; set; }
        public virtual JobCategory JobCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobAppoinment> JobAppoinments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeeked> JobSeekeds { get; set; }
    }
}
