//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBPORTAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;


    public partial class JobSeeker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobSeeker()
        {
            this.EmployerSelectsSeekers = new HashSet<EmployerSelectsSeeker>();
            this.JobAppoinments = new HashSet<JobAppoinment>();
            this.JobSeekeds = new HashSet<JobSeeked>();
            this.Resumes = new HashSet<Resume>();
        }
    
        public int JobSeekerId { get; set; }
        [Required(ErrorMessage = "User Name is Required")]
        public string JobSeekerUsername { get; set; }
        [Required(ErrorMessage = "Name is Required")]
        public string JobSeekerName { get; set; }
        [Required(ErrorMessage = "Contact Number is Required")]
        public string JobSeekerContactNo { get; set; }
        [Required(ErrorMessage = "Email is Required")]
        public string JobSeekerEmail { get; set; }
        [Required(ErrorMessage = "Password is Required")]
        [DataType(DataType.Password)]
        public string JobSeekerPassword { get; set; }
        public int EmployerId { get; set; }
        public string EducationalQualification { get; set; }
        public string ResumeFileName { get; set; }
        public string ProfilePictureName { get; set; }
    
        public virtual Employer Employer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployerSelectsSeeker> EmployerSelectsSeekers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobAppoinment> JobAppoinments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeeked> JobSeekeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resume> Resumes { get; set; }
    }
}
