//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBPORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume
    {
        public int ResumeId { get; set; }
        public string ResumePath { get; set; }
        public System.DateTime ResumeUploadDate { get; set; }
        public Nullable<System.DateTime> ResumeLastModifiedDate { get; set; }
        public int JobSeekerId { get; set; }
        public byte[] CvFile { get; set; }
        public string CvFileText { get; set; }
        public string CvFileName { get; set; }
    
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
